<?php
/** @var $this IntegerNet_DevDashboard_Block_Info_Patches */
$requiredPatches = $this->getMissingPatches();
$appliedPatches = $this->getAppliedPatches();
?>
<div class="content-header"><h3><?php echo $this->__('Security Patches') ?></h3></div>
<ul class="messages">
    <?php if (count($appliedPatches)): ?>
        <li class="success-msg">
            <strong><?php echo $this->__('Applied:'); ?></strong>
            <?php echo join(', ', $appliedPatches) ?>
        </li>
    <?php else: ?>
        <li class="warning-msg">
            <?php echo $this->__('%s not found. It might be that you applied patches but did not deploy this file.', '<strong>app/etc/applied.patches.list</strong>') ?>
        </li>
    <?php endif; ?>
    <?php if (count($requiredPatches)): ?>
        <li class="error-msg">
            <strong><?php echo $this->__('Missing:'); ?></strong>
            <?php echo join(', ', $requiredPatches) ?>
        </li>
    <?php endif; ?>
</ul>
