<?php
/** @var $this IntegerNet_DevDashboard_Block_Info_Patches */
$requiredPatches = $this->getMissingPatches();
$appliedPatches = $this->getAppliedPatches();
?>
<div class="content-header"><h3><?php echo $this->__('Security Patches') ?></h3></div>
<ul class="messages">
    <?php if (count($appliedPatches)): ?>
        <li class="success-msg">
            <strong><?php echo $this->__('Applied:'); ?></strong>
            <?php echo join(', ', $appliedPatches) ?>
        </li>
    <?php else: ?>
        <li class="warning-msg">
            <?php echo $this->__('%s not found. It might be that you applied patches but did not deploy this file.', '<strong>app/etc/applied.patches.list</strong>') ?>
        </li>
    <?php endif; ?>
    <?php if (count($requiredPatches)): ?>
        <li class="error-msg">
            <strong><?php echo $this->__('Missing:'); ?></strong>
            <?php echo join(', ', $requiredPatches) ?>
        </li>
        <li class="notice-msg">
            <p><?php echo $this->__('To download patches on the command line, use the following commands and follow the instructions:') ?></p>
            <pre style="padding: 1px; border: 1px solid #ccc; background-color: #eee; color: #666">export MAGEID=xxx
export MAGETOKEN=xxx
curl -k https://$MAGEID:$MAGETOKEN@www.magentocommerce.com/products/downloads/info/help</pre>
            <p><?php echo $this->__('To obtain <code>$MAGEID</code> and <code>$MAGETOKEN</code>, login to your account on magento.com and generate a token in Account Settings->Downloads Access Token. The MAGEID is shown at the top-left in your account page.') ?></p>
        </li>
    <?php endif; ?>
</ul>