<?php
/** @var $this IntegerNet_DevDashboard_Block_Info_Patches */
$requiredPatches = $this->getMissingPatches();
$appliedPatches = $this->getAppliedPatches();
?>
<div class="content-header"><h3><?php echo $this->__('Security Patches') ?></h3></div>
<ul class="messages">
    <?php if (count($requiredPatches)): ?>
        <li class="error-msg">
            <?php echo $this->__('Missing:'); ?>
            <?php echo join(', ', $requiredPatches) ?>
        </li>
    <?php endif; ?>
    <?php if (count($appliedPatches)): ?>
        <li class="success-msg">
            <?php echo $this->__('Applied:'); ?>
            <?php echo join(', ', $appliedPatches) ?>
        </li>
    <?php endif; ?>
</ul>
